[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/etern1ty/ros2_ws/build/launch_testing_examples/.pytest_cache
rootdir: /home/etern1ty/ros2_ws/src/src/examples/launch_testing/launch_testing_examples
plugins: launch-testing-1.0.4, ament-xmllint-0.12.10, ament-copyright-0.12.10, launch-testing-ros-0.19.7, ament-lint-0.12.10, ament-pep257-0.12.10, ament-flake8-0.12.10, colcon-core-0.15.1, cov-3.0.0
[1mcollecting ... [0m[1m
collected 9 items                                                              [0m

launch_testing_examples/check_msgs_launch_test.py [31mF[0m[31m                      [ 11%][0m
launch_testing_examples/check_multiple_nodes_launch_test.py [32m.[0m[31m            [ 22%][0m
launch_testing_examples/check_node_launch_test.py [32m.[0m[31m                      [ 33%][0m
launch_testing_examples/hello_world_launch_test.py [32m.[0m[31m                     [ 44%][0m
launch_testing_examples/record_rosbag_launch_test.py [32m.[0m[31m                   [ 55%][0m
launch_testing_examples/set_param_launch_test.py [32m.[0m[31m                       [ 66%][0m
test/test_copyright.py [32m.[0m[31m                                                 [ 77%][0m
test/test_flake8.py [32m.[0m[31m                                                    [ 88%][0m
test/test_pep257.py [32m.[0m[31m                                                    [100%][0m

=================================== FAILURES ===================================
[31m[1m_________ launch tests: launch_testing_examples.check_msgs_launch_test _________[0m

===================================================================================================================================================================================
FAIL: launch_testing_examples.check_msgs_launch_test.TestFixture.test_check_if_msgs_published
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/etern1ty/ros2_ws/src/src/examples/launch_testing/launch_testing_examples/launch_testing_examples/check_msgs_launch_test.py", line 43, in test_check_if_msgs_published
    with WaitForTopics([('chatter', String)], timeout=5.0):
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing_ros/wait_for_topics.py", line 113, in __enter__
    raise RuntimeError('Did not receive messages on these topics: ',
RuntimeError: ('Did not receive messages on these topics: ', {'chatter'})
[33m=============================== warnings summary ===============================[0m
test/test_flake8.py::test_flake8
test/test_flake8.py::test_flake8
  Warning: SelectableGroups dict interface is deprecated. Use select.

-- Docs: https://docs.pytest.org/en/stable/warnings.html
----------------------------- Captured stdout call -----------------------------
[INFO] [launch]: All log files can be found below /home/etern1ty/.ros/log/2024-02-01-00-47-17-194379-Etern1ty-14ALC6-35808
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [talker-1]: process started with pid [35826]
[talker-1] [INFO] [1706723238.247392089] [demo_node_1]: Publishing: 'Hello World: 1'
[talker-1] [INFO] [1706723239.247340524] [demo_node_1]: Publishing: 'Hello World: 2'
[talker-1] [INFO] [1706723240.247500115] [demo_node_1]: Publishing: 'Hello World: 3'
[talker-1] [INFO] [1706723241.247573274] [demo_node_1]: Publishing: 'Hello World: 4'
[talker-1] [INFO] [1706723242.247484365] [demo_node_1]: Publishing: 'Hello World: 5'
[INFO] [talker-1]: sending signal 'SIGINT' to process[talker-1]
[talker-1] [INFO] [1706723242.265572713] [rclcpp]: signal_handler(signum=2)
[INFO] [talker-1]: process has finished cleanly [pid 35826]
----------------------------- Captured stderr call -----------------------------
test_check_if_msgs_published (launch_testing_examples.check_msgs_launch_test.TestFixture) ... ERROR

======================================================================
ERROR: test_check_if_msgs_published (launch_testing_examples.check_msgs_launch_test.TestFixture)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/etern1ty/ros2_ws/src/src/examples/launch_testing/launch_testing_examples/launch_testing_examples/check_msgs_launch_test.py", line 43, in test_check_if_msgs_published
    with WaitForTopics([('chatter', String)], timeout=5.0):
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing_ros/wait_for_topics.py", line 113, in __enter__
    raise RuntimeError('Did not receive messages on these topics: ',
RuntimeError: ('Did not receive messages on these topics: ', {'chatter'})

----------------------------------------------------------------------
Ran 1 test in 5.050s

FAILED (errors=1)

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
- generated xml file: /home/etern1ty/ros2_ws/build/launch_testing_examples/pytest.xml -
=========================== short test summary info ============================
FAILED launch_testing_examples/check_msgs_launch_test.py::launch_testing_examples.check_msgs_launch_test
[31m=================== [31m[1m1 failed[0m, [32m8 passed[0m, [33m2 warnings[0m[31m in 19.06s[0m[31m ===================[0m
